name: Update Scam List
on:
  push:
    branches:
      - master
  schedule:
    - cron: "05 04 * * *"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        - name: Set up Python 3
          uses: actions/setup-python@v4
          with:
            python-version: 3.x
            cache: 'pip'

        - name: Set requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Set timezone to WIB Jakarta
          uses: szenius/set-timezone@v1.2
          with:
            timezoneLinux: "Asia/Jakarta"
            timezoneMacos: "Asia/Jakarta"
            timezoneWindows: "Indonesia Standard Time"
        - name: Run script
          run: python3 script.py

        - name: Commit antiscam.txt
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add antiscam.txt
            git commit -m "Update filtered scam URLs" || echo "No changes to commit"
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
